# Generated by Django 3.2.6 on 2021-08-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='유저이메일'),
        ),
    ]
