# Generated by Django 3.2.6 on 2021-08-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_boardmember_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='username',
            field=models.CharField(max_length=100, verbose_name='유저이름'),
        ),
    ]
